addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype" % "2.0")
addSbtPlugin("com.jsuereth"      % "sbt-pgp"      % "1.1.0")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt" % "2.4.0")
addSbtPlugin("de.heikoseeberger" % "sbt-header"   % "5.6.0")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.9.17")
